#!/usr/bin/env bash
#It displays  the content of the file /etc/passwd
while read -r line; do
    username=$(echo "$line" | cut -d: -f1)
    user_id=$(echo "$line" | cut -d: -f3)
    home_dir=$(echo "$line" | cut -d: -f6)
    echo "$username:$user_id:$home_dir"
done < /etc/passwd
