#!/usr/bin/env bash
#Displaying the content of the current directory
for file in *; do
    if [[ -f "$file" && "$file" != .* && "$file" == *-* ]]; then
        part_after_dash="${file#*-}"
        echo "$part_after_dash"
    fi
done
