#!/usr/bin/env bash
#This script manages 11-manage_my_process script
if [[ "$#" == "1" ]]; then
    if [[ "$1" == "start" ]]; then
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
    elif [[ "$1" == "stop" ]]; then
        if test -f /var/run/my_process.pid; then
            kill "$(cat /var/run/my_process.pid)"
        fi
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    elif [[ "$1" == "restart" ]]; then
        # stop program
        if test -f /var/run/my_process.
