#!usr/bin/env bash
#This stops 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
    kill "$pid"
    echo "Terminated"
else
    echo "Process not found"
fi
