#!/usr/bin/env bash
#This displays "To infinity and beyond" indefinitely and prints "I am invincible!!!" when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
