#!/usr/bin/env bash
#This script kills the 7-highlander process
pid=$(pgrep -f "7-highlander")

# If the process is found, kill it
if [ -n "$pid" ]; then
    kill "$pid"
    echo "Killed"
else
    echo "Process 7-highlander not found"
fi
